schemaVersion: 2.0 # The latest rio.yml schema.
# See: https://rio-docs.apple.com/docs/yaml_reference/schemav2.html for full
# documentation on all the features and options you can configure below.

# A list of pipeline specifications to define the jobs created for this project:
pipelines:

  # The following spec configures a pipeline to build and unit test the project,
  # then publish a deployable "slug" package for the application. This package
  # is then deployed via the PIE Application Orchestrator.
  - branchName: master # Runs any time a change is pushed to the master branch.
    build:
      # See https://docs.pie.apple.com/rio/build/templates/buildozer.html.
      template: buildozer:v1:publish
    deploy:
      pie: # configures the automated deployment to the PIE App Orchestrator.
        # Update environment: and availabilityZones: match to the # environment
        # key and availabilityZones you want to automatically deploy to:
        environment: dev # Your full environment key
        availabilityZones: # Specify the work unit
          - usspk05

  # The following spec configures a Pull Request Build for the master branch:
  - branchName: master
    build:
      # See https://docs.pie.apple.com/rio/build/templates/buildozer.html.
      template: buildozer:v1:prb
